### ISSUE TITLE
Treesitter help parser was renamed to vimdoc

### ISSUE THREAD

**Issue by doctorfree** [alanRizzo/dot-files#1]
Thanks for making your cool configs available. I like your Neovim config but discovered an error when trying it out.

The Treesitter help parser was renamed to `vimdoc`. To fix this I modified the `ensure_installed` setting as follows:

```
lua/aesthetic/_treesitter.lua:  ensure_installed = { "python", "lua", "vim", "javascript", "vimdoc" },
```

Next, explore your tmux config!

**Comment by alan-rizzo** [comment]
@doctorfree thanks for the review and the fix. I will update it ASAP.

**Comment by alanRizzo** [comment]
@doctorfree thanks for the review and the fix. I will update it ASAP.

https://github.com/alanRizzo/dot-files/commit/2bc1760566883e49cd329b97204008bb9cd3d6f2
